config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  get '/users/edit' => 'users#edit', :as => 'edit_user'
  resources :users, :except => [:edit] do
    resources :destinations
      resources :photos
  end
  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'users#login'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  geocoded_by :place
  after_validation :geocode

  def place
    "#{city} #{country}"
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :destination
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # validates :email, :uniqueness => true
  has_many :destinations
  has_many :photos, :through => :destinations

  def self.koala(auth)
      access_token = auth['token']
      facebook = Koala::Facebook::API.new(access_token)
      facebook.get_object("me?fields=first_name,last_name,age_range,picture,locale,bio,email,photos")
  end

  def destination_coordinates
    destinations.map do |destination|
      { lat: destination.latitude , lng: destination.longitude }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :fetch_user

  private

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]

      session[:user_id] = nil unless @current_user
    end
  end

  def authorize_user
    redirect_to root_path unless @current_user.present?
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :authorize_user, :except => [:index, :show]

  def index
    #how do we write all destinations for user id. Can an instance variable in a different contoller be called?
#    @destinations = Destination.all
    @user = User.find params[:user_id]
    @destinations = @user.destinations
  end

  def new
    @destination = Destination.new
  end

  def create
    destination = @current_user.destinations.create destination_params
    # @destination = @current_user.destinations.create destination_params
    # req = Cloudinary::Uploader.upload(params[:file])
    # @user = @current_user
    # @desination.image = req["url"]
    redirect_to user_destination_path(@current_user, destination)
  end

  def edit
    @destination = Destination.find params[:id]
  end

  def update
    @destination = Destination.find params[:id]
    # @destination.photos.destroy_all unless params[:destination_photos].empty?
    params[:destination_photos].present? && params[:destination_photos].each do |photo|
      req = Cloudinary::Uploader.upload(photo)
      p = Photo.create(:image => req["url"])
      @destination.photos << p
      # Or maybe @destination.photos.create(:image => req["url"])
    end
    @destination.update destination_params
    @user = @current_user
    redirect_to user_destination_path(@current_user, @destination)
  end

  def show
    @destination = Destination.find params[:id]
  end

  def destroy
    destination = Destination.find params[:id]
    destination.destroy
    redirect_to user_destinations_path(@current_user)
  end

  private
  def destination_params
    params.require(:destination).permit(:city, :country, :start_date, :trip_synopsis, :must_do, :must_see, :must_eat, :end_date, :who, :purpose, :favorite_part, :map_link, :destination_photos)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photos.all
  end

  def new
  end

  def create

  end

  def destroy
    # /users/:id/destination/:id/photos
    # Delete request
  end

  def show
    # @destination = params[:photo_id]
    # @photos = @destination.photos

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def login
   @user = User.koala(request.env['omniauth.auth']['credentials'])
  end
  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to user_destinations_path(user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorise_user, :only => [:index, :show]
  before_action :check_for_user, :only => [:edit, :update]

  def index
    @users = User.all
  end

  def login
   @user = User.koala(request.env['omniauth.auth']['credentials'])
   facebook_id = @user["id"]
   @current_user = User.find_or_create_by(:facebook_id => facebook_id)
   @current_user.first_name = @user["first_name"]
   @current_user.last_name = @user["last_name"]
   @current_user.email = @user["email"]
   @current_user.password_digest = "efielkwj"
   @current_user.save
   session[:user_id] = @current_user.id
   redirect_to user_destinations_path(@current_user)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_destinations_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    req = Cloudinary::Uploader.upload(params[:file])
    @user = @current_user
    @user.image = req["url"]
    if @user.update(user_params)
      redirect_to user_destinations_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find params[:id]
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to user_destinations_path(user)
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email, :birthdate, :current_city, :current_city, :fav_destination, :about_me, :password_confirmation, :image)
  end

  def check_for_user
    redirect_to new_user_path unless @current_user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/destinations/_form.html.erb
<!-- //Images in scrolling layout

//two side-by-side divs with -->
<!-- <h1>Listing photos</h1>
<div class="col-md-12 destination_row">
  <%# @photos.in_groups_of(3) do |group| %>
    <div class="row">
      <%# group.compact.each do |photo| %>
        <div class="col-xs-4">
          <%#= image_tag photo.file_url, :width => '100%' if photo.file.present?%>
          <h4><%#= link_to photo.title, photo %></h4>
          <%#= photo.description %>
        </div>
      <%# end %>
    </div>
  <%# end %>
</div> -->
<%= form_for([@current_user, @destination], :html => {:multipart => true}) do |f| %>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_date, 'Start date of trip' %>
    <%= f.date_field :start_date, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :end_date, 'End date of trip'%>
    <%= f.date_field :end_date, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :trip_synopsis, 'Trip Synopsis' %>
    <%= f.text_area :trip_synopsis, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :must_eat, 'Must eat?' %>
    <%= f.text_field :must_eat, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :must_see, 'Must see?' %>
    <%= f.text_field :must_see, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :must_do, 'Must do?' %>
    <%= f.text_field :must_do, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :who, 'Who did you go with?' %>
    <%= f.text_field :who, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :purpose, 'Why did you go?' %>
    <%= f.text_field :purpose, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :favorite_part, 'What was your favorite part?' %>
    <%= f.text_area :favorite_part, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :destination_photos %>
    <%= file_field_tag("destination_photos[]", :multiple => true ) %>
  </div>

  <div class="form-group">
    <%= f.label :map_link, 'Place an embed link for Tripcipe, Google MyMaps or Four Square' %>
    <%= f.text_area :map_link, :class => 'form-control' %>
  </div>

  <%= f.submit %>

<% end %>

app/views/destinations/edit.html.erb
<h1>Edit Destination</h1>
<%= render :partial => 'form' %>
<div class="controls">
  <!-- This is morally wrong -->
  <%= button_to 'Delete', user_destination_path, :method => :delete, :data => { :confirm => "Are you sure?" } %>
</div>

app/views/destinations/index.html.erb
<script>
  var destinationCoordinates = <%== @user.destination_coordinates.to_json %>;
</script>

<div class = 'row profile_heading'>
  <div class="col-md-4 destination_row profile_pic">
      <%= cl_image_tag @user.image, :width=>200, :height=>200, :gravity=>"auto", :class => 'thumb' %>
  </div>
  <div class="col-md-8 destination_row">
    <h1 class="welcome_message"><%= @user.first_name %>'s Travels!</h1>
    <p id="aboutme"><%= @user.about_me %></p>
  </div>

</div>
<div style='width: 100%;'>
  <div id="multi_markers" style='width:100%; height: 400px;'>
  </div>
</div>
<div class = 'row'>
<% @destinations.each do |destination| %>
  <div class="col-md-3 destination_row">
    <a href="<%=user_destination_path(@user, destination)%>">
    <div class="destination_thumb" style="background-image: url(<%= destination.photos.first.image if destination.photos.any? %>); background-color: rgba(148, 197, 204, 0.5); background-size: cover; ">
      <%= link_to destination.city, user_destination_path(@user, destination)%> <%= destination.country%>
    </div>
  </a>
  </div>
<%end %>
</div>
<div>

app/views/destinations/new.html.erb
<h1>New Destination</h1>
<%= render :partial => 'form' %>

app/views/destinations/show.html.erb
<div class="row">
    <div class="col-md-12 destination_header" data-latitude="<%=@destination.latitude%>" data-longitude="<%=@destination.longitude%>">
        <h1><%= @destination.city %>,
            <%= @destination.country %></h1>
    </div>
</div>
<%if @destination.photos.any? %>
<%if @destination.photos.count < 7 %>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="4000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <%(1...@destination.photos.count).each do |number| %>
        <li data-target="#carousel-example-generic" data-slide-to="<%= number %>"></li>
        <% end %>

    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="<%= @destination.photos.first.image %>" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <% @destination.photos.drop(1).each do |photo| %>
        <div class="item">
            <img src="<%=photo.image%>" alt="...">
            <!-- <div class="carousel-caption">
            ...
          </div> -->
        </div>
        <% end %>

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<%else%>
<div class="row destination-photos">
    <% @destination.photos.each do |photo| %>
    <div class="col-xs-6 col-md-3">
        <%= cl_image_tag photo.image, :width=>171, :height=>180, :gravity=>"auto", :crop=>"thumb", :class => 'thumbnail' %>
    </div>
    <% end %>
    <!-- ... -->
</div>
<% end %>
<% end %>

<div class='row destination_info'>

    <div class="col-md-6 destination_row">
        <h3>
            Trip Details</h3>
        <ul>
            <li><%= @destination.start_date.strftime "Month Traveled: %B" if @destination.start_date%></li>
            <li>Traveled with:
                <%= @destination.who %></li>
            <li>Traveled for:
                <%= @destination.purpose %></li>
            <li>Best Part:
                <%= @destination.favorite_part %></li>
            <li>Must Eat:
                <%= @destination.must_eat %></li>
            <li>Must See:
                <%= @destination.must_see %></li>
            <li>Must Do:
                <%= @destination.must_do %></li>

            <!-- <li><%#= @destination. %></li> need to add tips-->
        </ul>
    </div>
    <div class="col-md-6 destination_row">
        <!-- add blurb  -->
        <h3>
            My trip...</h3>
        <p id="synopsis"><%= @destination.trip_synopsis %></p>
    </div>
</div>
<div class='city_map'>
  <%== @destination.map_link %>
</div>
<div class='row'>
<div class="col-md-10"></div>
<div class="col-md-2 edit_link">
    <%= link_to "Edit Destination", edit_user_destination_path(@current_user, @destination), :class => 'edit_link' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelapp</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyA3EclmXThMoeo8-91du7fjDWpxtsycqjc"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <%= cloudinary_js_config %>
</head>
<body>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '509273182605027',
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
  <div class="container">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand brand_font" href="/">Trace</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <!-- <span class="sr-only">(current)</span> -->
      <% if @current_user.present? %>
        <li> <%= link_to "#{@current_user.first_name}'s Home", user_destinations_path(@current_user)%></li>
        <li><%= link_to "New Destination", new_user_destination_path(@current_user)%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Destinations <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @current_user.destinations.each do |destination| %>
                  <li>
                  <%= link_to destination.city, user_destination_path(@current_user, destination)%>
                  </li>
            <%end %>
          </ul>
        </li>
        <% end %>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user.present? %>
        <li><%= link_to "Edit Profile", edit_user_path %></li>
        <li><%= link_to "Logout #{ @current_user.first_name }", login_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to 'Sign up', new_user_path %></li>
        <li><%= link_to 'Login', login_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
</div>
</body>
<footer> &copy 2016</footer>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class = 'row hero_image'>
  <div class="col-md-12">
  <h1 class="hero">Trace</h1>
  <p class="tagline">your tracks around the world</p>
  </div>
</div>
<!-- <div class ="col-md-8">
<div class ="col-md-4">

</div>
</div> -->
<!-- <div class = 'row'>
  <div class="col-md-4 destination_thumb">thailand</div>
  <div class="col-md-4 destination_thumb">spain</div>
  <div class="col-md-4 destination_thumb">iceland</div>
</div> -->
<section class="module content">
  <div class="row1">
  </div>
<section>
<section class="module parallax parallax-1">
  <div class="container">
    <h1>Limitless</h1>
  </div>
</section>
 <section class="module content">
    <div class="row1">
    <p class="quotes">Travel is the only thing you buy that makes you richer
   </p>
  </div>
</section>
<section class="module parallax parallax-2">
 <div class="container">
    <h1>Raw</h1>
  </div>
</section>
<section class="module content">
    <div class="row1">
    <p class="quotes">Not all those who wander are lost -J.R.R. Tolkien
   </p>
  </div>
</section>
<section class="module parallax parallax-3">
   <div class="container">
      <h1>Magical</h1>
    </div>
</section>
</div>
</div>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/new.html.erb
<h1>Photos#new</h1>
<p>Find me in app/views/photos/new.html.erb</p>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/session/new.html.erb
<h1>Login</h1>
<div class="row login_row">
    <div class="col-md-6 login_form">
        <%= form_tag '/login' do %>
        <div class="form-group">
            <%= label_tag :email, nil, :autofocus => true %>
            <%= text_field_tag :email, nil, :class => 'form-control' %>
            <!-- Because it doesn't have form for because second argument is usually the value to need to pass through nil -->
        </div>
        <div class="form-group">
            <%= label_tag :password %>
            <%= password_field_tag :password, nil, :class => 'form-control'%>
        </div>
        <%= submit_tag 'Login' %>
        <% end %>
    </div>
    <div class="col-md-6 fbarea">
        <div class="facebook_div">
            <div><%=link_to image_tag('fb.jpg'), '/auth/facebook', :class => 'fb_button' %></div>
        </div>
    </div>


</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for(@current_user, :html => {multipart: true}) do |f| %>

  <div class="form-group">
  <%= f.label :image %>
  <%= f.cl_image_upload :image, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :birthdate %>
  <%= f.date_field :birthdate, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :current_city%>
  <%= f.text_field :current_city, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :fav_destination %>
  <%= f.text_field :fav_destination, :class => 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :about_me %>
  <%= f.text_area :about_me, :class => 'form-control' %>
  </div>
<% if @current_user.facebook_id.nil? %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, :autofocus => true, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>
  </div>
<% end %>  
  <!-- <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div> -->

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p><%= user.first_name %></p>
  <p><%= user.email %></p>
<% end %>

app/views/users/login.html.erb
<%= image_tag @user['picture']['data']['url'].to_s %>
<%= @user['name'] %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="col-md-6 fbarea">
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :autofocus => true, :required => true, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, :required => true, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :class => 'form-control' %>
</div>
  <%= f.submit "Sign up" %>
<% end %>
</div>

<div class="col-md-6 fbarea">
    <div class="facebook_div">
        <div><%=link_to image_tag('fb.jpg'), '/auth/facebook', :class => 'fb_button' %></div>
    </div>
</div>